### ISSUE TITLE
DSL needs cleaning

### ISSUE THREAD

**Issue by mikefarah** [DiUS/pact-js-provider#5]
Both provider_states_for and providerState take a function as a parameter, that function is given 'done' but done is never called (and doesn't look like it should be).

Also, there is an empty 'it'.

**Comment by elliottmurray** [comment]
The done is legacy before I moved to mocha so you are probably right but unless this is a major issue I am probably going to wind down this project in favour of 

https://github.com/pact-foundation/pact-js

The work I've done on this project we've merged into the above and improved on. I'll keep up with small bug fixes here, however. I'll post a note in the README

**Comment by mikefarah** [comment]
Oh cool, I'll check that project out.

**Comment by mikefarah** [comment]
Also, you probably should mention this project has been deprecated in favour of pact-js on the readme.
